#!/bin/bash

# Export environment variables from the hos t
if [ -f /etc/environment ]; then
  set -a
  source /etc/environment
  set +a
fi

### Check if running with root privileges ###
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 
  exit 1
fi

### Resize Partition ###
echo "Resizing the file system..."

root_device=/dev/$(lsblk -no PKNAME,MOUNTPOINT | awk '$2 == "/" {print $1}')
partition_suffix=$(lsblk -no KNAME,MOUNTPOINT | awk '$2 == "/" {gsub(/.*[^0-9]/, "", $1); print $1}')

if [[ $root_device == /dev/sd* ]]; then
  partition_number="${partition_suffix}"
else
  partition_number="p${partition_suffix}"
fi

sudo growpart ${root_device} ${partition_suffix}
sudo resize2fs ${root_device}${partition_number}

### Setup based on robot model ###
read -p "Specify robot model. Options: $(tput bold)rosbot$(tput sgr0) (ROSbot Series) or $(tput bold)husarion_ugv$(tput sgr0) (for Lynx / Panther): " robot_model

if [[ "$robot_model" != "rosbot" && "$robot_model" != "husarion_ugv" ]]; then
  echo "Invalid robot model selected. Please choose either '$(tput bold)rosbot$(tput sgr0)' or '$(tput bold)husarion_ugv$(tput sgr0)'."
  exit 1
fi

echo "Robot model: ${robot_model}"

$(dirname "$0")/robots/${robot_model}/custom_config.sh

cp -rp $(dirname "$0")/robots/${robot_model}/${ROS_DISTRO}/* /home/husarion
dpkg -i $(dirname "$0")/robots/${robot_model}/motd_$(uname -m).deb
cp $(dirname "$0")/robots/${robot_model}/netplan.yaml /etc/netplan/01-network-manager-all.yaml
bash /usr/lib/husarion/custom_config_${robot_model}.sh

if [ ! -d /home/husarion/.ros ]; then
  mkdir /home/husarion/.ros
fi
chown husarion:husarion /home/husarion/.ros

sudo chmod 600 /etc/netplan/01-network-manager-all.yaml

# Generating new SSH credentials
sudo echo "" > /root/.ssh/authorized_keys
sudo echo "" > /root/.ssh/known_hosts
sudo echo "" > /home/husarion/.ssh/authorized_keys
sudo echo "" > /home/husarion/.ssh/known_hosts
sudo rm -rf /etc/ssh/ssh_host_*

ssh-keygen -A
# systemctl restart ssh.service 

# Print success message
echo ""
echo "Configuration files copied successfully for robot model \"$robot_model\" and ROS version \"$ros_version\""
