network:
  version: 2
  renderer: networkd

  ethernets:

    all-eths:
      match:
        name: eth*
      dhcp4: false
      dhcp6: false
      optional: true
      addresses:
        - 10.15.20.3/24
      routes:
        - to: default
          via: 10.15.20.1
      nameservers:
        addresses: [8.8.8.8]
