services: 
  rviz:
    image: husarion/rviz:noetic
    container_name: rviz
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./default.rviz:/root/.rviz/default.rviz
    environment: 
      - DISPLAY=${DISPLAY:-:0}
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://127.0.0.1:11311}
      - ROS_IP=${ROS_IP:-127.0.0.1}
      # - LIBGL_ALWAYS_SOFTWARE=1

  frame-transformer:
    image: husarion/rviz:noetic
    container_name: frame-transformer
    network_mode: host
    environment: 
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://127.0.0.1:11311}
      - ROS_IP=${ROS_IP:-127.0.0.1}
    command: rosrun tf static_transform_publisher 0 0 0 0 0 0 laser camera_link 0