services:
  astra:
    image: husarion/astra:humble
    container_name: astra
    devices:
      - /dev/bus/usb/
    volumes:
      - ./robot-configs/astra-params.yaml:/ros2_ws/install/astra_camera/share/astra_camera/params/astra_mini_params.yaml
    command: ros2 launch astra_camera astra_mini.launch.py

  rplidar:
    image: husarion/rplidar:humble
    container_name: rplidar
    restart: unless-stopped
    devices:
      - /dev/ttyRPLIDAR:/dev/ttyUSB0
    command: >
        ros2 launch sllidar_ros2 sllidar_launch.py
        serial_baudrate:=${RPLIDAR_BAUDRATE:-256000}

  microros:
    image: husarion/micro-ros-agent:humble
    container_name: microros
    restart: unless-stopped
    devices:
      - ${SERIAL_PORT:?err}
    command: serial -D $SERIAL_PORT serial -b 576000 # -v6

  rosbot:
    image: husarion/rosbot:humble
    container_name: rosbot
    restart: unless-stopped
    command: ros2 launch rosbot_bringup bringup.launch.py

  rviz:
    image: husarion/rviz2:humble
    container_name: rviz
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./robot-configs/default.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1

  frame_transformer:
    image: husarion/rviz2:humble
    command: ros2 run tf2_ros static_transform_publisher 0 0 0 0 0 0 base_link laser
