x-common-config:
  &common-config
  restart: unless-stopped
  network_mode: host
  ipc: host
  environment:
    - RMW_IMPLEMENTATION
    - FASTRTPS_DEFAULT_PROFILES_FILE
    - CYCLONEDDS_URI

services:

  rosbot-xl:
    image: husarion/rosbot-xl:humble
    container_name: rosbot-xl
    <<: *common-config
    command: ros2 launch rosbot_xl_bringup bringup.launch.py mecanum:=${MECANUM:-True}

  microros:
    image: husarion/micro-ros-agent:humble
    container_name: microros
    <<: *common-config
    # ports:
    #   - "8888:8888/udp"
    command: ros2 run micro_ros_agent micro_ros_agent udp4 --port 8888
