x-common-config:
  &common-config
  restart: unless-stopped
  network_mode: host
  tty: true
  environment:
    - ROS_MASTER_URI=${ROS_MASTER_URI:-http://127.0.0.1:11311}
    - ROS_IP=${ROS_IP:-127.0.0.1}

services:

  ros-master:
    image: ros:noetic-ros-core
    container_name: ros-master
    <<: *common-config
    command: roscore

  rosbot:
    image: husarion/rosbot:noetic
    container_name: rosbot
    <<: *common-config
    devices:
      - ${SERIAL_PORT:?err}
    env_file:
      - serial.env
    command: roslaunch --wait rosbot_bringup rosbot_docker.launch

  rplidar:
    image: husarion/rplidar:noetic
    container_name: rplidar
    <<: *common-config
    devices:
      - /dev/ttyRPLIDAR:/dev/ttyUSB0
    command: roslaunch --wait rplidar_ros rplidar_a3.launch
    # command: roslaunch --wait rplidar_ros rplidar.launch # for LIDARs in older ROSbots (A2M8 with red circle around the sensors)

  astra:
    image: husarion/astra:noetic
    container_name: astra
    <<: *common-config
    devices:
      - /dev/bus/usb
    command: roslaunch --wait astra_camera astra.launch

