network:
  version: 2
  renderer: networkd

  ethernets:

    all-eths:
      match:
        name: eth*
      dhcp4: yes
      dhcp6: yes
      optional: true
      addresses:
        - 10.15.20.3/24
        - 192.168.77.2/24
