---
network:
  version: 2
  renderer: NetworkManager

  ethernets:

    all-eths:
      match:
        name: eth*
      dhcp4: no
      dhcp6: no
      optional: true
      addresses:
        - 192.168.77.2/24

    all-enps:
      match:
        name: enP8p1s*
      dhcp4: no
      dhcp6: no
      optional: true
      addresses:
        - 192.168.77.2/24

  wifis:
    # ========================================
    # standard Wi-Fi config (client)
    # ========================================
    wlan0:
      dhcp4: true
      dhcp6: true
      optional: true
      access-points:
        "PLACE_YOUR_WIFI_SSID_HERE":
          password: "PLACE_YOUR_WIFI_PASSWORD_HERE"

    # ========================================
    # access point Wi-Fi config
    # replace "channel" with the number permitted in your country
    # https://en.wikipedia.org/wiki/List_of_WLAN_channels
    # ========================================
    # wlan0:
    #   dhcp4: yes
    #   addresses:
    #     - 192.168.78.1/24
    #   access-points:
    #     "rosbotap":
    #       band: "5GHz"
    #       channel: "149"
    #       mode: "ap"
    #       password: "husarion"
