x-restart-policy:
  &restart-policy
  restart: unless-stopped

x-ros-config:
  &ros-config
  network_mode: host
  ipc: host
  pid: host
  shm_size: '256mb'
  environment:
    - ROS_DOMAIN_ID
    - FASTRTPS_DEFAULT_PROFILES_FILE=/shm-only.xml

services:

  # ============ basic services ============
  rosbot:
    image: husarion/rosbot:humble-0.11.0-20231227
    <<: [*restart-policy, *ros-config]
    devices:
      - ${SERIAL_PORT:?err}
    command: >
      ros2 launch rosbot_bringup combined.launch.py 
        mecanum:=${MECANUM:-False}
        serial_port:=$SERIAL_PORT 
        serial_baudrate:=576000

  rplidar:
    image: husarion/rplidar:humble
    <<: [*restart-policy, *ros-config]
    devices:
      - /dev/ttyRPLIDAR:/dev/ttyUSB0
    command: >
        ros2 launch sllidar_ros2 sllidar_launch.py
        serial_baudrate:=${RPLIDAR_BAUDRATE:-256000} 

  astra:
    image: husarion/astra:humble
    <<: [*restart-policy, *ros-config]
    volumes:
      - ./config/astra.yaml:/ros2_ws/install/astra_camera/share/astra_camera/params/astra_mini_params.yaml
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.0'
    devices:
      - /dev/bus/usb/
    command: ros2 launch astra_camera astra_mini.launch.py
 
  # ============ web ui services ============

  foxglove-datasource:
    image: husarion/foxglove-bridge:humble-0.7.3-20231213
    <<: [*restart-policy, *ros-config]
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765 capabilities:=[clientPublish,parameters,parametersSubscribe,services,connectionGraph,assets]

  foxglove:
    image: husarion/foxglove:1.81.0
    <<: *restart-policy
    ports:
      - 8080:8080
      - "[::]:8765:8765"
    volumes:
      - ./config/foxglove_layout.json:/foxglove/default-layout.json
    environment:
      - DS_TYPE=foxglove-websocket
      - DS_PORT=8765
      - DS_HOST=172.17.0.1
      - UI_PORT=8080
      - DISABLE_CACHE=true
      - DISABLE_INTERACTION=false

  # ============ ROS 2 Router ============

  # quick start:
  # export ROS_LOCALHOST_ONLY=1 # without this WHITELIST_INTERFACES="127.0.0.1" doesn't work
  # ./ros_driver_start.sh
  # docker compose up ros2router

  ros2router:
    image: husarnet/ros2router:1.5.0
    <<: *restart-policy
    network_mode: host
    ipc: host
    # ipc: shareable
    pid: host
    volumes:
      - ./config/filter.yaml:/filter.yaml
    environment:
      - ROS_DISTRO
      - ROS_LOCALHOST_ONLY=1
      - DISCOVERY_SERVER_LISTENING_PORT=11811
      - DISCOVERY_SERVER_ID=0

