# Comments:
#   * This is a temporary solution allowing shared memory communication between host and docker container when
#     using Fast DDS. To be removed when user will be able to change this permission to something else than 0644 
#     (https://github.com/eProsima/Fast-DDS/blob/master/thirdparty/boost/include/boost/interprocess/permissions.hpp#L100) 
#
#  ** If the FASTRTPS_DEFAULT_PROFILES_FILE or CYCLONEDDS_URI envs are defined, then we need to bind mount the volume
#     with the DDS config to the container  
#
# *** Optional envs the ROS user may want to set - we need to pass them to the container

x-common-config:
  &common-config
  restart: unless-stopped
  network_mode: host
  ipc: host
  user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000} # *
  volumes:
    - /etc/group:/etc/group:ro                  # *
    - /etc/passwd:/etc/passwd:ro                # *
    - /etc/shadow:/etc/shadow:ro                # *
    - /home/husarion/.ros:/home/husarion/.ros   # *
    - ${FASTRTPS_DEFAULT_PROFILES_FILE:-dummy_volume_fastdds}:${FASTRTPS_DEFAULT_PROFILES_FILE:-/dummy_volume_fastdds}  # **
    - ${CYCLONEDDS_PATH:-dummy_volume_cyclonedds}:${CYCLONEDDS_PATH:-/dummy_volume_cyclonedds}                          # **
  environment:
    - RMW_IMPLEMENTATION              # ***
    - FASTRTPS_DEFAULT_PROFILES_FILE  # ***
    - CYCLONEDDS_URI                  # ***
    - ROS_LOCALHOST_ONLY              # ***

services:
  astra:
    image: husarion/astra:humble
    container_name: astra
    <<: *common-config
    devices:
      - /dev/bus/usb/
    command: ros2 launch astra_camera astra_mini.launch.py

  rplidar:
    image: husarion/rplidar:humble
    container_name: rplidar
    <<: *common-config
    devices:
      - /dev/ttyRPLIDAR:/dev/ttyUSB0
    command: >
        ros2 launch sllidar_ros2 sllidar_launch.py
        serial_baudrate:=${RPLIDAR_BAUDRATE:-256000}

  microros:
    image: husarion/micro-ros-agent:humble
    container_name: microros
    <<: *common-config
    devices:
      - ${SERIAL_PORT:?err}
    command: ros2 run micro_ros_agent micro_ros_agent serial -D $SERIAL_PORT serial -b 576000 # -v6

  rosbot:
    image: husarion/rosbot:humble
    container_name: rosbot
    <<: *common-config
    command: ros2 launch rosbot_bringup bringup.launch.py

volumes:
  dummy_volume_fastdds:
  dummy_volume_cyclonedds: